export interface IndustryPreset {
  label: string
  accountEmail: string
  businessName: string
  businessCategory: string
  phoneNumber: string
  emailAddress: string
  streetAddress: string
  city: string
  region: string
  country: string
  postalCode: string
  logoUrl: string
  backgroundUrl: string
  overview: string
  services: string
  aboutUs: string
  businessDescription: string
  serviceArea: string
  toneOfVoice: string
  instructions: string
  maxPages: string
  paletteIndex: number
}

export const INDUSTRY_PRESETS: IndustryPreset[] = [
  {
    label: 'Artisan Bakery',
    accountEmail: 'test@example.com',
    businessName: 'Sunrise Bakery',
    businessCategory: 'Food & Beverage',
    phoneNumber: '5031234567',
    emailAddress: 'hello@sunrisebakery.com',
    streetAddress: '42 Maple Avenue',
    city: 'Portland',
    region: 'Oregon',
    country: 'US',
    postalCode: '97201',
    logoUrl: 'https://irt-cdn.multiscreensite.com/7536fe2010ed4f7ea68e21d0cb868e01/dms3rep/multi/ice_cream_logo_b_w-18-300x300.svg',
    backgroundUrl: 'https://irt-cdn.multiscreensite.com/7536fe2010ed4f7ea68e21d0cb868e01/dms3rep/multi/sign_icecream_shop-1000x1108.jpg',
    overview: 'A family-owned artisan bakery specializing in sourdough breads, seasonal pastries, and custom celebration cakes using locally sourced ingredients.',
    services: 'Sourdough bread, pastries, custom cakes, coffee',
    aboutUs: 'Founded in 2010 by the Nguyen family, Sunrise Bakery has been serving Portland with handcrafted baked goods made fresh every morning.',
    businessDescription: 'Artisan bakery open 7 days a week, specializing in sourdough and seasonal pastries.',
    serviceArea: 'Greater Portland metro area',
    toneOfVoice: 'ENTHUSIASTIC',
    instructions: 'Emphasize the artisan and handcrafted nature of products. Include a section for seasonal specials.',
    maxPages: '5',
    paletteIndex: 5,
  },
  {
    label: 'Italian Restaurant',
    accountEmail: 'test@example.com',
    businessName: 'Trattoria della Nonna',
    businessCategory: 'Food & Beverage',
    phoneNumber: '3121234567',
    emailAddress: 'info@trattorianonna.com',
    streetAddress: '820 N Michigan Avenue',
    city: 'Chicago',
    region: 'Illinois',
    country: 'US',
    postalCode: '60611',
    logoUrl: '',
    backgroundUrl: '',
    overview: 'An authentic Italian trattoria serving traditional recipes passed down through three generations, featuring house-made pastas and wood-fired pizzas.',
    services: 'Pasta, pizza, antipasti, wine, private dining, catering',
    aboutUs: 'Trattoria della Nonna has brought the warmth of a Roman kitchen to Chicago since 1998. Every dish is made from scratch using imported Italian ingredients.',
    businessDescription: 'Authentic Italian trattoria with house-made pasta and wood-fired pizza in the heart of Chicago.',
    serviceArea: 'Downtown Chicago and surrounding neighborhoods',
    toneOfVoice: 'CONVERSATIONAL',
    instructions: 'Evoke warmth, family tradition, and Italian heritage. Mention the wine list and private dining room.',
    maxPages: '6',
    paletteIndex: 3,
  },
  {
    label: 'Law Firm',
    accountEmail: 'test@example.com',
    businessName: 'Hargrove & Associates',
    businessCategory: 'Legal Services',
    phoneNumber: '2121234567',
    emailAddress: 'contact@hargrovelaw.com',
    streetAddress: '350 Fifth Avenue, Suite 4100',
    city: 'New York',
    region: 'New York',
    country: 'US',
    postalCode: '10118',
    logoUrl: '',
    backgroundUrl: '',
    overview: 'A full-service litigation and corporate law firm representing individuals and businesses in complex legal matters across New York and nationally.',
    services: 'Corporate law, litigation, employment law, real estate, estate planning',
    aboutUs: 'Hargrove & Associates was founded in 1992 with a commitment to aggressive advocacy and personalized client service. Our team of 30 attorneys brings decades of combined courtroom experience.',
    businessDescription: 'Full-service law firm specializing in corporate law and litigation with offices in Manhattan.',
    serviceArea: 'New York, New Jersey, Connecticut',
    toneOfVoice: 'AUTHORITATIVE',
    instructions: 'Project confidence, expertise, and trustworthiness. Highlight case results and areas of practice. Include a clear call to action to schedule a consultation.',
    maxPages: '7',
    paletteIndex: 4,
  },
  {
    label: 'Dental Office',
    accountEmail: 'test@example.com',
    businessName: 'Bright Smile Dental',
    businessCategory: 'Healthcare',
    phoneNumber: '5121234567',
    emailAddress: 'hello@brightsmile.com',
    streetAddress: '1200 Congress Avenue',
    city: 'Austin',
    region: 'Texas',
    country: 'US',
    postalCode: '78701',
    logoUrl: '',
    backgroundUrl: '',
    overview: 'A modern family dental practice offering comprehensive preventive, cosmetic, and restorative dentistry in a comfortable, anxiety-free environment.',
    services: 'Cleanings, whitening, Invisalign, veneers, implants, emergency dental care',
    aboutUs: 'Dr. Sarah Chen and her team have been helping Austin families achieve healthy, beautiful smiles since 2015. We use the latest technology to make every visit comfortable and efficient.',
    businessDescription: 'Modern family dental practice offering preventive, cosmetic, and restorative care in Austin, TX.',
    serviceArea: 'Austin and surrounding Travis County',
    toneOfVoice: 'PROFESSIONAL',
    instructions: 'Emphasize comfort, modern technology, and family-friendly environment. Include online booking prompt and new patient specials.',
    maxPages: '6',
    paletteIndex: 1,
  },
  {
    label: 'Real Estate Agency',
    accountEmail: 'test@example.com',
    businessName: 'Coastal Realty Group',
    businessCategory: 'Real Estate',
    phoneNumber: '3051234567',
    emailAddress: 'homes@coastalrealty.com',
    streetAddress: '901 Brickell Avenue',
    city: 'Miami',
    region: 'Florida',
    country: 'US',
    postalCode: '33131',
    logoUrl: '',
    backgroundUrl: '',
    overview: 'A boutique real estate agency specializing in luxury waterfront properties, condos, and single-family homes across Miami-Dade and Broward counties.',
    services: 'Buyer representation, seller representation, property management, luxury listings, investment properties',
    aboutUs: 'Coastal Realty Group has closed over $500M in real estate transactions since 2008. Our bilingual team of 15 agents specializes in helping clients find their dream home in South Florida.',
    businessDescription: 'Boutique luxury real estate agency serving Miami-Dade and Broward with expert local market knowledge.',
    serviceArea: 'Miami-Dade, Broward, and Palm Beach counties',
    toneOfVoice: 'CONVERSATIONAL',
    instructions: 'Highlight luxury lifestyle, waterfront properties, and local market expertise. Include featured listings section and agent profiles.',
    maxPages: '8',
    paletteIndex: 1,
  },
  {
    label: 'Fitness Studio',
    accountEmail: 'test@example.com',
    businessName: 'Apex Fitness Studio',
    businessCategory: 'Health & Fitness',
    phoneNumber: '3101234567',
    emailAddress: 'train@apexfitness.com',
    streetAddress: '8500 Sunset Boulevard',
    city: 'Los Angeles',
    region: 'California',
    country: 'US',
    postalCode: '90069',
    logoUrl: '',
    backgroundUrl: '',
    overview: 'A premium boutique fitness studio offering small-group strength training, HIIT, and yoga classes led by certified coaches in a high-energy environment.',
    services: 'Strength training, HIIT, yoga, personal training, nutrition coaching, class memberships',
    aboutUs: 'Apex Fitness was founded by two former Olympic athletes who believe that everyone deserves elite-level coaching. With 12 certified trainers and state-of-the-art equipment, we help members hit goals they never thought possible.',
    businessDescription: 'Boutique fitness studio in West Hollywood offering strength, HIIT, and yoga with certified coaches.',
    serviceArea: 'West Hollywood, Beverly Hills, and the greater Los Angeles area',
    toneOfVoice: 'ENTHUSIASTIC',
    instructions: 'High energy and motivational tone. Highlight results, community, and coach credentials. Include class schedule and free trial offer.',
    maxPages: '6',
    paletteIndex: 3,
  },
  {
    label: 'Hair Salon & Spa',
    accountEmail: 'test@example.com',
    businessName: 'Lumière Salon & Spa',
    businessCategory: 'Beauty & Wellness',
    phoneNumber: '6151234567',
    emailAddress: 'book@lumieresalon.com',
    streetAddress: '2100 Charlotte Avenue',
    city: 'Nashville',
    region: 'Tennessee',
    country: 'US',
    postalCode: '37203',
    logoUrl: '',
    backgroundUrl: '',
    overview: 'A full-service luxury salon and spa offering hair color, cuts, keratin treatments, facials, and massage therapy in a chic, welcoming environment.',
    services: 'Hair cuts, color, highlights, keratin, facials, waxing, massage, bridal packages',
    aboutUs: 'Lumière opened in 2016 with the mission to create a true luxury experience accessible to everyone. Our stylists train annually in Paris and New York to stay ahead of the latest trends.',
    businessDescription: 'Luxury salon and spa in Nashville offering hair, skin, and wellness services with internationally trained stylists.',
    serviceArea: 'Nashville and surrounding Davidson County',
    toneOfVoice: 'WITTY',
    instructions: 'Sophisticated yet approachable. Emphasize the luxury experience and expert stylists. Include online booking and seasonal promotions.',
    maxPages: '6',
    paletteIndex: 4,
  },
  {
    label: 'Auto Repair Shop',
    accountEmail: 'test@example.com',
    businessName: 'Eagle Eye Auto Repair',
    businessCategory: 'Automotive',
    phoneNumber: '7201234567',
    emailAddress: 'service@eagleyeauto.com',
    streetAddress: '4400 East Colfax Avenue',
    city: 'Denver',
    region: 'Colorado',
    country: 'US',
    postalCode: '80220',
    logoUrl: '',
    backgroundUrl: '',
    overview: 'A family-owned full-service auto repair shop specializing in domestic and import vehicles, offering honest diagnostics, quality repairs, and competitive pricing.',
    services: 'Oil changes, brake repair, engine diagnostics, transmission, tires, AC service, inspections',
    aboutUs: "Eagle Eye Auto Repair has served the Denver community for over 20 years. ASE-certified mechanics and a commitment to transparency mean you always know exactly what you're paying for and why.",
    businessDescription: 'Full-service ASE-certified auto repair shop in Denver serving domestic and import vehicles.',
    serviceArea: 'Denver metro area',
    toneOfVoice: 'INFORMATIVE',
    instructions: 'Build trust through transparency and expertise. Highlight ASE certifications, warranty on repairs, and free estimates. Avoid overly technical jargon.',
    maxPages: '5',
    paletteIndex: 3,
  },
  {
    label: 'Veterinary Clinic',
    accountEmail: 'test@example.com',
    businessName: 'Paws & Claws Veterinary Clinic',
    businessCategory: 'Veterinary Services',
    phoneNumber: '2061234567',
    emailAddress: 'care@pawsandclaws.com',
    streetAddress: '1500 Queen Anne Avenue N',
    city: 'Seattle',
    region: 'Washington',
    country: 'US',
    postalCode: '98109',
    logoUrl: '',
    backgroundUrl: '',
    overview: 'A compassionate full-service veterinary clinic providing preventive care, surgery, dentistry, and urgent care for dogs, cats, and small animals.',
    services: 'Wellness exams, vaccinations, dental cleanings, surgery, diagnostics, urgent care, microchipping',
    aboutUs: 'Dr. Marcus Webb and his team of four veterinarians have been caring for Seattle pets since 2011. We treat every patient like our own and offer extended hours to fit your busy schedule.',
    businessDescription: 'Compassionate full-service vet clinic in Queen Anne serving dogs, cats, and small animals.',
    serviceArea: 'Queen Anne, Magnolia, Ballard, and greater Seattle',
    toneOfVoice: 'CONVERSATIONAL',
    instructions: 'Warm, caring, and reassuring tone. Highlight the full range of services and emergency availability. Include a new patient form prompt.',
    maxPages: '6',
    paletteIndex: 2,
  },
  {
    label: 'Photography Studio',
    accountEmail: 'test@example.com',
    businessName: 'Golden Hour Photography',
    businessCategory: 'Photography',
    phoneNumber: '4151234567',
    emailAddress: 'hello@goldenhourphoto.com',
    streetAddress: '525 Market Street',
    city: 'San Francisco',
    region: 'California',
    country: 'US',
    postalCode: '94105',
    logoUrl: '',
    backgroundUrl: '',
    overview: 'A boutique photography studio specializing in weddings, portraits, and brand photography, known for capturing authentic emotion and cinematic natural light.',
    services: 'Wedding photography, engagement sessions, portraits, newborn, brand & commercial, event photography',
    aboutUs: 'Lead photographer Jamie Torres has captured over 300 weddings and brand campaigns across California and beyond. With an editorial background and a documentary approach, Golden Hour turns moments into lasting art.',
    businessDescription: 'Boutique SF photography studio specializing in weddings, portraits, and brand imagery with a cinematic style.',
    serviceArea: 'San Francisco Bay Area and destination worldwide',
    toneOfVoice: 'WITTY',
    instructions: 'Artistic, evocative, and personal. Let the photography speak — use minimal text and lots of visual references. Include an inquiry form and investment guide download.',
    maxPages: '7',
    paletteIndex: 5,
  },
]
